"""empty message

Revision ID: 205b5f8d76aa
Revises: 14727616d911
Create Date: 2022-06-02 21:32:20.159732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205b5f8d76aa'
down_revision = '14727616d911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student', sa.String(length=100), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('date_enroll', sa.String(length=100), nullable=True),
    sa.Column('date_close', sa.String(length=100), nullable=True),
    sa.Column('score', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    # ### end Alembic commands ###
