"""empty message

Revision ID: 3ac673a76d04
Revises: cd2340c8be83
Create Date: 2022-10-05 23:17:01.819674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac673a76d04'
down_revision = 'cd2340c8be83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('phone', sa.String(length=50), nullable=True))
    op.drop_column('student', 'telefone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('telefone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('student', 'phone')
    # ### end Alembic commands ###
