"""empty message

Revision ID: 98a20531e924
Revises: 205b5f8d76aa
Create Date: 2022-06-22 22:31:02.002901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a20531e924'
down_revision = '205b5f8d76aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'holder_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('holder_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
