"""empty message

Revision ID: bab8ec43b3da
Revises: 98a20531e924
Create Date: 2022-10-05 20:18:36.325785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab8ec43b3da'
down_revision = '98a20531e924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('avatar', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
