"""empty message

Revision ID: cd2340c8be83
Revises: bab8ec43b3da
Create Date: 2022-10-05 23:15:40.204442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2340c8be83'
down_revision = 'bab8ec43b3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('telefone', sa.String(length=100), nullable=True))
    op.drop_column('student', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('student', 'telefone')
    # ### end Alembic commands ###
